apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: cloud-native-workshop
spec:
  user: 
    number: 5
    password: openshift
  source:
    gitURL: https://github.com/mcouliba/cloud-native-workshop
    gitBranch: master
  infrastructure:
    che:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: eclipse-che.v7.2.0
    etherpad:
      enabled: false
    gogs:
      enabled: false
      image:
        name: quay.io/wkulhanek/gogs-operator
        tag: v0.9.0
    nexus:
      enabled: false
    pipeline:
      enabled: false
      operatorHub:
        channel: dev-preview
        clusterServiceVersion: openshift-pipelines-operator.v0.5.2
    project:
      enabled: true
      name: cn-project
    serviceMesh:
      enabled: false
      elasticSearchOperatorHub:
        channel: preview
        clusterServiceVersion: elasticsearch-operator.4.1.15-201909041605
      jaegerOperatorHub:
        channel: stable
        clusterServiceVersion: jaeger-operator.v1.13.1
      kialiOperatorHub:
        channel: stable
        clusterServiceVersion: kiali-operator.v1.0.5
      serviceMeshOperatorHub:
        channel: "1.0"
        clusterServiceVersion: servicemeshoperator.v1.0.0
    squash:
      enabled: false
    workshopper:
      enabled: true