apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: devops-workshop
spec:
  user: 
    number: 5
    password: r3dh4t1!
  source:
    gitURL: https://github.com/mcouliba/devops-workshop
    gitBranch: master
  infrastructure:
    che:
      enabled: true
      operatorHub:
        channel: stable
        clusterServiceVersion: eclipse-che.v7.2.0
    etherpad:
      enabled: false
    gogs:
      enabled: true
      image:
        name: quay.io/wkulhanek/gogs-operator
        tag: v0.9.0
    nexus:
      enabled: false
    pipeline:
      enabled: true
      operatorHub:
        channel: dev-preview
        clusterServiceVersion: openshift-pipelines-operator.v0.5.2
    serviceMesh:
      enabled: false
      elasticSearchOperatorHub:
        channel: preview
        clusterServiceVersion: elasticsearch-operator.4.1.15-201909041605
      jaegerOperatorHub:
        channel: stable
        clusterServiceVersion: jaeger-operator.v1.13.1
      kialiOperatorHub:
        channel: stable
        clusterServiceVersion: kiali-operator.v1.0.5
      serviceMeshOperatorHub:
        channel: "1.0"
        clusterServiceVersion: servicemeshoperator.v1.0.0
    # guide:
    #   enabled: true
    #   gitRepositoryLabPath: mcouliba/cloud-native-labs
    #   gitRepositoryLabReference: debugging
    #   gitRepositoryGuidePath: dwojciec/debugging-lab-summit-2019
    #   gitRepositoryGuideReference: master
    #   gitRepositoryGuideContext: instructions
    #   gitRepositoryGuideFile: _debugging-workshop.yml
    squash:
      enabled: false
    workshopper:
      enabled: true