apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloud-native-workshop-operator
  template:
    metadata:
      labels:
        name: cloud-native-workshop-operator
    spec:
      serviceAccountName: cloud-native-workshop-operator
      containers:
        - name: cloud-native-workshop-operator
          # Replace this with the built image name
          image: quay.io/mcouliba/cloud-native-workshop-operator:v1
          command:
          - cloud-native-workshop-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cloud-native-workshop-operator"
